version: "3.7"
services:
  collect-vbn:
    build: ./collect
    volumes:
      - filevolume:/files
    environment:
      GTFS_ID: vbn
      GTFS_RT_URL: http://gtfsr.vbn.de/gtfsr_connect.bin
      GTFS_SCHEDULE_URL: http://www.connect-info.net/opendata/gtfs/connect-nds-toplevel/ztqxhoilmd
      PING_RT_URL: https://hc-ping.com/<censored> # insert your real URL here
      PING_SCHEDULE_URL: https://hc-ping.com/<censored> # insert your real URL here
