version: "3.3"
services:

# vbn (verkehrsverbund bremen/niedersachen) services:

  collect-vbn:
    build: ./collect
    env_file:
      - global.env
      - vbn.env
    volumes:
      - filevolume:/files

  import-vbn:
    image: dystonse-gtfs-data:local
    env_file: 
      - global.env
      - vbn.env
    volumes:
      - filevolume:/files
    depends_on:
      - db
    command: sh -c "dystonse-gtfs-data -v --password $$MYSQL_PASSWORD --dir /files/$$GTFS_DATA_SOURCE_ID/ import --record --predict --cleanup automatic"

  analyse-vbn:
    build: ./analyse
    env_file:
      - global.env
      - vbn.env
    volumes:
      - filevolume:/files
    depends_on:
      - db

# vrn (verkehrsverbund rhein-neckar) services:

  collect-vrn:
    build: ./collect
    env_file:
      - global.env
      - vrn.env
    volumes:
      - filevolume:/files

  import-vrn:
    image: dystonse-gtfs-data:local
    env_file:
      - global.env
      - vrn.env
    volumes:
      - filevolume:/files
    depends_on:
      - db
    command: sh -c "dystonse-gtfs-data  -v --password $$MYSQL_PASSWORD --dir /files/$$GTFS_DATA_SOURCE_ID/ import --record --predict --cleanup automatic"

  analyse-vrn:
    build: ./analyse
    env_file:
      - global.env
      - vrn.env
    volumes:
      - filevolume:/files
    depends_on:
      - db
