version: "3.3"
services:
  db:
    image: mysql:8
    volumes:
      - dbvolume:/var/lib/mysql
      - ./secrets:/secrets
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /secrets/mysql_root_password
      MYSQL_USER: dystonse
      MYSQL_PASSWORD_FILE: /secrets/mysql_dystonse_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - db
    environment:
      PMA_HOST: db
  
  dystonse-gtfs-data:
    build: https://github.com/dystonse/dystonse-gtfs-data.git
    command: echo "hello world from dystonse-gtfs-data!"
    # not sure if this is enough to build an image that does nothing 
    # but that other containers can use as a parent image
  
  # collect-services and import-services are defined in docker-compose.override.yml 
  # which is not commited into the repository because of contained secret values
  # see docker-compose.sample.yml

volumes:
  dbvolume:
  filevolume: